### ISSUE TITLE
multiple ENSEMBL IDs mapping to single gene

### ISSUE THREAD

**Issue by vetmohit89** [ShixiangWang/IDConverter#10]
Dear Wang,

I used nanocount to get counts data for deseq2 analysis. Now I converted these ENST ids to gene symbol using ID convereter tool. But I have mutliple ENST ids representing data from the same gene. How to deal with this situation?
![image](https://github.com/ShixiangWang/IDConverter/assets/110649675/dfda036c-6ab7-4419-99f0-aac865159200)

**Comment by ShixiangWang** [comment]
Hi, the ID starts with `ENST` means it is 'transcript', so of course you will see they are mapped to the same gene. If you have interested in performing DEG on the transcript level, just go to downstream analysis with the transcript IDs. If you just want to do gene-level analysis, you should get a quantification of gene-level from your upstream analysis (or collapse the transcript level to gene level by summing all counts of the same genes).
