### ISSUE TITLE
Not able to convert ENST ids to gene name

### ISSUE THREAD

**Issue by vetmohit89** [ShixiangWang/IDConverter#8]
I followed this code to convert ENST ids to gene name using gtf file as input file. Not sure why it is not able to read ENST object.

library(IDConverter)
enst_ids <- read.table("enst.txt", header = FALSE)
gtf <- rtracklayer::import('gencode.v42.annotation.gtf')
gtf_df=as.data.frame(gtf)
gene_names <- convert_custom(enst_ids, from = "transcript_id", to = "gene_name", dt = gtf_df, multiple = FALSE)

Error in convert(dt, x, from, to, multiple) : 
  Cannot find your input in 'from', please check the identifier type!
![enst ids](https://user-images.githubusercontent.com/110649675/210483589-c7cf4758-07a8-4b09-94ff-329c93323396.jpg)

**Comment by ShixiangWang** [comment]
Could you show your `gtf_df` with a snapshot? And also try changing `enst_ids` to `enst_ids[[1]]` or `enst_ids$V1`.

**Comment by vetmohit89** [comment]
After changing enst_ids.. It is still giving me the same error. 

> gene_names <- convert_custom(enst_ids$v1, from = "transcript_id", to = "gene_name", dt = gtf_df, multiple = FALSE)
Error in convert(dt, x, from, to, multiple) : 
  Cannot find your input in 'from', please check the identifier type!
> gene_names <- convert_custom(enst_ids[[1]], from = "transcript_id", to = "gene_name", dt = gtf_df, multiple = FALSE)
Error in convert(dt, x, from, to, multiple) : 
  Cannot find your input in 'from', please check the identifier type!

Here is screenshot of gtf datafram.
![gtf2](https://user-images.githubusercontent.com/110649675/210581046-b12b7816-68ef-4f77-a2c0-b4572bfb694c.jpg)
![gtf](https://user-images.githubusercontent.com/110649675/210581048-cbad3b98-2984-4c91-a93e-c069969ecf26.jpg)

**Comment by vetmohit89** [comment]
Thanks. It works now. I am just wondering if I have data in the form of chromosome and position, how can I convert them to gene ID. Does "FROM" command take two input columns?

![chr_and_position](https://user-images.githubusercontent.com/110649675/210843475-44670b0e-5f01-406c-92f8-23bc2dea87ac.jpg)

**Comment by ShixiangWang** [comment]
No, IDConverter cannot handle this case. You need to use tools like bedtools, GenomicRanges, pyranges to overlap the chromosome position to specific gene regions and derive the corresponding gene ID/names.
